### ISSUE TITLE
Improve the release engineering

### ISSUE THREAD

**Issue by merks** [eclipse-birt/birt#1286]
### Tasks
- [x]  Make Eclipse Marketplace work with the new location
- [X]  Update website download locations
- [X]  Update project download locations

### Description
The setup should produce a usable workspace amenable to contribution. The target platform should be modernized to use newer dependencies; ideally it should be easier to maintain it and to update it to newer dependencies in the future.  It should be easier (possible) to do local Tycho builds.  It should be easier to produce nightly, milestone, and release builds.  There appear to be too many products (*.product) and too many update sites (category.xml).  It's not clear why those are all needed and who all consumes those.  Simplification and reduction of these would help streamline the releng process. 

Perhaps the EPP Eclipse IDE for Java and Report Developers could be revived, but the build results are of a quality not consumable by SimRel:

https://download.eclipse.org/oomph/archive/reports-extra/birt-snapshot/download.eclipse.org/birt/update-site/snapshot/index.html

**Comment by merks** [comment]
I've been trying to get the tests to run locally, with some success but also some failure, but now I see the build uses `-Dmaven.test.skip=true` which is most disconcerting!

**Comment by wimjongman** [comment]
Do you mean the main build? I can imagine that because that one is only to publish the result. All PR checks are running with tests. E.g.:

https://github.com/eclipse/birt/actions/runs/4773353790/jobs/8486375628?pr=1271

**Comment by merks** [comment]
My branch that I was working on, unknown to me, was badly out of date.   😢   So I'm reworking the changes to get back to the point I was at yesterday.   And there are many interrupts today we shall see how far I get today...

**Comment by wimjongman** [comment]
Thanks, Ed. No rush. 

@eclipse/technology-birt-committers Please read this thread. We are going to improve our releng and with that our overall ability to execute.

**Comment by merks** [comment]
@wimjongman 

To really use the latest of everything, e.g., Platform, GEF and so on, you'd need to use Java 17 for some things, e.g., for the JustJ JRE used for the products.  Does anything speak against switching to Java 17 which is the latest LTS version?

**Comment by wimjongman** [comment]
We can go to Java 17.

**Comment by wimjongman** [comment]
We have been moved to our own organisation:

https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/3185

**Comment by merks** [comment]
FYI, I will wait for this IP review to complete

https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/8506

These are all the BIRT defined products:

![image](https://github.com/eclipse-birt/birt/assets/208716/00f36114-80e4-4223-8ac6-10a3c39fcd4f)

These are all the BIRT defined sites:

![image](https://github.com/eclipse-birt/birt/assets/208716/67afc3c4-1abe-4d86-bee3-a80f5aaec328)

How will "we" go about deciding which products and sites are import to keep and to publish?

**Comment by wimjongman** [comment]
@hvbtup @speckyspooky @claesrosell please comment on the above https://github.com/eclipse-birt/birt/issues/1286#issuecomment-1557276627 Which of the products and sites are used by your consumers?

**Comment by speckyspooky** [comment]
@wimjongman 
From our side the main products are:
- "BIRT Report Designer All-In-One"
- "BIRT Engine Runtime" (OSGi)

**Comment by claesrosell** [comment]
> 
We are not using any product, we are:
* Consuming various Birt plugins via our target platform
* Installing the "Birt Report Designer" -feature into Eclipse IDE.

**Comment by csut4735** [comment]
> @wimjongman From our side the main products are:
> 
> * "BIRT Report Designer All-In-One"
> * "BIRT Engine Runtime" (OSGi)

That's all we use too.

**Comment by hvbtup** [comment]
We are using:

    "BIRT Report Designer All-In-One"
    "BIRT Engine Runtime" without OSGi

**Comment by chloetz** [comment]
We are using:

"BIRT Report Designer All-In-One"

"BIRT Engine Runtime" with OSGi


Von: Henning von Bargen ***@***.***
Gesendet: Dienstag, 23. Mai 2023 13:39
An: eclipse-birt/birt
Cc: Loetz, Christophe; Team mention
Betreff: Re: [eclipse-birt/birt] Improve the release engineering (Issue #1286)


We are using:

"BIRT Report Designer All-In-One"

"BIRT Engine Runtime" without OSGi

**Comment by merks** [comment]
The following is an observation.  This is what's published for the most recent release:

![image](https://github.com/eclipse-birt/birt/assets/208716/44c41937-5e8b-47bb-b95c-74e3e6497fb1)

There is a **single** update site:

https://download.eclipse.org/birt/update-site/4.13.0/

So I think there are just two products there along with some other zips that I have yet to understand their content and purpose, and there is only a single update site...

So while the build produces many more products and site, these aren't published currently.

A goal here is to streamline the production of the site as well as any/all useful/necessary associated packaged results.   I will make the assumption that things not currently leading to published results are not needed in the build and that no one is relying on building such things themselves directly.  I want to state that assumption explicitly so that someone can contradict it if it's wrong.

**Comment by merks** [comment]
@wimjongman 

BTW, it will be much easier for me/us if I have commit rights such that I can help with things such as target platform updates, 
enabling more tests, including managing their shared launch configurations so you can easily run them in the IDE, setting up build jobs and so on.   I got most of the tests working now, except the UI tests, because I'm not sure they will run on the server without some configuration.   Also, I gave up on this test because there are so many errors and failures and I don't understand well what they are testing:

![image](https://github.com/eclipse-birt/birt/assets/208716/7e4ae102-f1cf-4d25-bc34-1e1c0b2b03a9)

**Comment by speckyspooky** [comment]
There are many many test based on the full history of BIRT. I don't know if you are able to understand all in full.
This is a very hugh challenge.

The marked line is based on a special spudsoft-emitter UserProperty.
With that property you can control the handling of empty rows of the spudsoft-excel emitter.
And this test (my interpretation) check the correct working based on a fix in the past.

But I see many many more issue-testcases which would be good like standard test cases.

**Comment by merks** [comment]
Mostly I'm trying to make sense of the tests so I know how to launch each of them and which ones will need further attention from you experts.  So far I have this set of launchers that I'm working on and will include in the Git Repo so that they are reusable:

![image](https://github.com/eclipse-birt/birt/assets/208716/0936ff99-2541-4d28-851e-62ced88548a1)

But this is a work-in-progress...

**Comment by merks** [comment]
@wimjongman 

I am under the impression that BIRT is working towards a 4.14 release.  But the POM, feature, and bundle versions are all (mostly all) still 4.13.  I want to manage updating these easily in a more automated way so I'm analyzing the current state of all the versions.

Once thing that seems a little concerning to me is the class/jar files in the Git repository:

- https://github.com/eclipse-birt/birt/tree/master/common/javax.xml.rpc/javax/xml/rpc
- https://github.com/eclipse-birt/birt/tree/master/common/org.apache.axis/lib
- https://github.com/eclipse-birt/birt/tree/master/common/org.apache.derby.core
- https://github.com/eclipse-birt/birt/tree/master/common/org.w3c.sac/lib

I only noticed these because they don't have 4.13 versions, which makes sense.  But one has to wonder where these come from and how they might be updated in the future, if/when necessary.

**Comment by wimjongman** [comment]
Hi Ed @merks. Thanks for fixing this. I always did this manually. I have a PR pending with this fix but I could not get the build going using the latest Eclipse deps.

**Comment by wimjongman** [comment]
Regarding the comment https://github.com/eclipse-birt/birt/issues/1286#issuecomment-1575497550. Maybe you can create a new issue out of this.

**Comment by merks** [comment]
I thought I would go insane if I had to do it manually.  So tedious and error prone.  I have a simple Java class that does all the work so next time will be very easy...

**Comment by ruspl-afed** [comment]
> I have a simple Java class that does all the work so next time will be very easy...

Do you a have another class to help with PR review? 😊

**Comment by ruspl-afed** [comment]
> Any thoughts, questions, or concerns?

I have positive impression from using this magic. Two things to mention:
1) for "release" builds it is not yet clear for me how it could be "tailored" with legacy releases that project already has.
2) cleanup procedure for old nightly and stable builds is not yet clear for me, since standard "archive" UI is overlapped by generated index.html pages

**Comment by merks** [comment]
I did a fake old release on one of the projects just by coping a release repository folder to the correct/expected location with the correct/expected name.  I could try that again, but in this case, it's much trickier with all these special download artifacts because those are recorded as repository properties during the promotion process, so it's not easy to manage applying it to an older release.  Do you think that's important or can we make a fresh start in the new location leaving the other stuff where it is right now for a while?

Nightly builds are self cleaning.  The `-retain 5` argument specifies the cutoff number to retain.  The milestone builds are also self cleaning.  As soon a milestone is published with a higher branding version `-version-iu org.eclipse.birt.feature` all the current milestones are deleted and that new one with the new higher version becomes the only child at that point, so assuming that one doesn't build milestones for years without increasing versions, that should be limiting.  If necessary an option to limit the number could be implemented.

The retention policy is documented on the sites:

>  This composite update site references the 4 most recent successful nightly builds

> This composite update site references x successful milestone builds. These sites will be retained only until the first successful milestone build of the next Xyz release.

**Comment by speckyspooky** [comment]
Question to the new build process. I have seen that the new version avoid the creation of the test segments like before.
So all tests will be handled during the complete build process.
These test segments had 2 functions:
1. organize the test process into chapters and so we get an structured test organization
2. the next segment will only be started if the segements are done before successfully

On my failed build of the weekend I saw that the build process go through till the end,
create all zip-files and so on. But at the end the process figured out that there was an test failure.

At the end the full build process runs longer like the version before due to the changed error handling and we loss the test segmentation.

Therefore my questions:
- Is there an option to improve the handling to stop on failure of unit tests?
- And does anyone miss the test segment imformation?

The important topic for me is the failure handling that the process tries to stop after an test failure was detected.

**Comment by speckyspooky** [comment]
I forgott to say, I like the improvement of the build process and also the enhancements of the test cases!

**Comment by merks** [comment]
I did add `--fail-at-end` here so that all the test run:

https://github.com/eclipse-birt/birt/blob/3b72e4b9f121433508e5fa1eec1a5d2603844b01/.github/workflows/ci.yml#L46

This can also cause things to run that otherwise wouldn't run at all.   That can of course be removed and then the build will stop as soon as one test fails.  That has the advantage that the first failure can be noticed more quickly and the disadvantage that if 5 different test suites/projects have failures, you won't notice a second failure until you've fixed the first one so you might need to do 5 builds before you get that far (which is why I changed it so that I could run the full build and know about all the failures while testing the huge number of changes that I had made.)   But it's probably good to change it back again now.  Note that without the "segmentation"  in the ci.yml, the tests run much earlier in the build; in the past they ran after the full build...

**Comment by merks** [comment]
FYI, 

The first published builds are available at this **temporary** location:

https://download.eclipse.org/birt/updates-tmp/nightly/latest/

I want to ensure that the whole end-to-end processing, including creating a release, produces the correct structure.  Eventually I will delete the entire updates-tmp folder and begin producing build results in the updates folder.  All the links appear to be working correctly...

**Comment by merks** [comment]
I've tested the whole process, so there are milestones and releases here now:

https://download.eclipse.org/birt/updates-tmp/

Also, I'm migrated the 4.12.0 and 4.13.0 releases into the new structure so those are present as well.

If no one has any concerns or significant changes they'd like to see, I will now build into the updates folder and will migrated the 4.12.0 and 4.13.0 releases into the folder as well.  OK?  

Of course I won't produce a release build for 4.14.0 until we are ready for that!

**Comment by merks** [comment]
Before we produce a release, I'd like to figure out why there are so few proper licenses being used and also where the unsigned content comes from:

https://download.eclipse.org/oomph/archive/reports-extra/birt/download.eclipse.org/birt/updates-tmp/release/4.14.0/index.html

I know some unsigned content problems come from very old Orbit bundles jar-signed with weak algorithms that are no longer recognized as jar signed, but that's not the case for all of them.

**Comment by merks** [comment]
FYI, the new update sites have been built at the proper location:

https://download.eclipse.org/birt/updates/index.html

The sites include those for the two previous releases:

- https://download.eclipse.org/birt/updates/release/4.12.0
- https://download.eclipse.org/birt/updates/release/4.13.0

These p2 update sites will now always be available:

- https://download.eclipse.org/birt/updates/nightly/latest
- https://download.eclipse.org/birt/updates/milestone/latest
- https://download.eclipse.org/birt/updates/release/latest

The sites are self-documenting.  Note that each site provides a link to the git commit for that site's build.

**Comment by speckyspooky** [comment]
The new download area looks very great.
Is it possible to link the archive folder too? 

So we would have all together.

**Comment by merks** [comment]
Anything is possible... 

That being said, things are in the archive for a reason, i.e., because we don't generally expect **nor want** people to be using such _very old_ things when we have new-improved-and-better things.

There's a lot of old stuff here:

https://archive.eclipse.org/justj/?file=birt/downloads

What kind of links specifically did you have in mind?  I.e., where would such links appear, to what would they link, and why would a user need (to know) that?  (And to what does "all" refer to in "have all together"?)

**Comment by csut4735** [comment]
Rather than moving old stuff to (yet another) new place, I would prefer you leave it where it can be found by people using old links, and insert a link to the latest download directory there.

--
Colin

On 8 Jun 2023, at 4:52 pm, Ed Merks ***@***.***> wrote:

﻿

Anything is possible...

That being said, things are in the archive for a reason, i.e., because we don't generally expect nor want people to be using such very old things when we have new-improved-and-better things.

There's a lot of old stuff here:

https://archive.eclipse.org/justj/?file=birt/downloads

What kind of links specifically did you have in mind? I.e., where would such links appear, to what would they link, and why would a user need (to know) that? (And to what does "all" refer to in "have all together"?)

**Comment by speckyspooky** [comment]
I haven't said that the old link will be deactivated.
I prefer 1 place to find all. It makes no sense to have 2 incomplete places/download areas.

It would be nice to have also on the new area the archive links.

**Comment by speckyspooky** [comment]
@merks
I would say to have by default a link to the current archive. 
My favorit would be an archive area with the links of all old versions (releases) and there according sources.

**Comment by merks** [comment]
@csut4735 

I did not move anything from anywhere to anywhere.  

I think maybe you are suggesting that perhaps

https://download.eclipse.org/birt/update-site/snapshot/

could be a composite that references:

https://download.eclipse.org/birt/updates/nightly/latest

and that

https://download.eclipse.org/birt/update-site/latest/

could be a composite that references

https://download.eclipse.org/birt/updates/release/latest

So that those will just continue to work  But I'm reading between the lines.  In any case, the new structure cannot "just be moved" into the old poorly-manged structure...

@speckyspooky 

Similarly, I asked 3 specific questions and I see no answers.   The "new area" is  a whole web of pages so please be explicit about "this page should have this link to this thing because...".  I.e., show the link and state where (on which page) it is located.  Also, you talk about something being incomplete, but I don't know what is incomplete.  I assert that the new locations are 100% complete and contain **everything** in the old locations.  And I really mean everything, so if there is a thing that you believe is missing/incomplete, please be explicit what that thing is.

**Comment by speckyspooky** [comment]
I will give later a detailed summary.
The point is that some users use older versions from archive.
That was for example the reason why the archive link with the old versions was created in the current download page.

My supplier of a specific Bird-framing use version 4.10-osgi, so I need a link to the old version.

**Comment by wimjongman** [comment]
Hi. I agree with @merks  to NOT point to the archive in the stuff that Ed is building for us. The Archives will still be there prominently on the website but it should not be part of our current downloads pages. 

So
1. The Archives will stay where they are: https://archive.eclipse.org/birt/downloads/drops/
2. The archives are featured on our main page: https://eclipse-birt.github.io/birt-website/
3. The stuff that Ed is building does not carry any old stuff.

Good compromise?

**Comment by merks** [comment]
Indeed, I see now that we were (probably) talking about the two links on this page:

https://eclipse-birt.github.io/birt-website/

That's the second checkbox at the top of this issue that Wim added the other day.  And yes, that will certainly need proper consideration before we are complete here!  I imagine that, as Wim suggest, archive will continue to point where it does now.  And that downloads will point here:

https://download.eclipse.org/birt/updates/

where the user can navigate to whatever they are most interested and can get at the downloads if they wish, e.g., here the latest release, which is currently 4.13.0 and provides the linked downloads:

![image](https://github.com/eclipse-birt/birt/assets/208716/d3288bed-60a5-4daf-a5f1-335a52156b70)

**Comment by wimjongman** [comment]
Unless you feel strongly about it, I suggest replacing 'glyph' with 'icon'. Technically you are correct but do normal people know what glyphs are?

**Comment by wimjongman** [comment]
> why we shouldn't have on the lefthand side also a chapter "archive"?

Because we don't want people to go there and download old stuff. 

You can now respond with: "But it is on the homepage as well" (I play chess ;). , to which I respond that I would rather also remove it from the homepage because we don't want to encourage people to get old stuff.

**Comment by merks** [comment]
@speckyspooky 

One thing to note is that the links in the left column also correspond to the breadcrumb links across the top.  I would need to extend JustJ p2 publishing framework to accommodate extra links.  That's not a huge challenge I guess, but I also note that there's a whole bunch of "old stuff" in archives and just pointing at the root also seems somewhat unhelpful:

https://archive.eclipse.org/justj/?file=birt

Do we really need folks to go there?  I would hope not so much...

**Comment by speckyspooky** [comment]
OK, I agree with the argument to hand only the latest version on the building page.

@wimjongman
The experience of our support of the project and my experiences avid to delete the archive. 
There are many infrastructure dependencies over all versions.
For example you cannot force to change by default based on the BIRD project to move to latest Java version.
I remember on our unsolved issue with Rhino and Java 11 vs 17.
So yes, it make sense to have the archive.

**Comment by wimjongman** [comment]
Ok, I have updated marketplace and the main website. 

I installed latest from the marketplace in the latest 2023-06 but I ran into this issue:

https://github.com/eclipse-birt/birt/issues/1131

We should release 4.14 ASAP.

**Comment by speckyspooky** [comment]
Please wait with 4.14 I would add my small viewer changes immediately.

But it is a good idea to speed up 4.14.

**Comment by merks** [comment]
@wimjongman 

FYI, I fixed all the licenses and am looking at unsigned content, some of which I've tracked down and will hopefully have fixed:

![image](https://github.com/eclipse-birt/birt/assets/208716/aca0eb7d-4a0c-41d2-83bb-f16a90065d59)

I also noticed this is open:

https://github.com/eclipse-birt/birt/pull/995/files

I see this version is available as an OSGi artifact so I will determine if we can't just reuse that...

https://repo1.maven.org/maven2/org/apache/derby/derby/10.16.1.1/

**Comment by merks** [comment]
Given yesterday was the deadline for the latest contribution for 2023-06, **absolutely not**!

In the ideal world (at this point) we'd have a release ready for June 14th that works well with the 2023-06 packages. 

The release seems planned for October:

https://projects.eclipse.org/projects/technology.birt/releases/4.14.0

It's been many years since a review!

**Comment by wimjongman** [comment]
> Given yesterday was the deadline for the latest contribution for 2023-06, absolutely not!
😂

**Comment by merks** [comment]
@wimjongman 

I'm not sure how the website works.  I think it would be good to include it in the project setup and to include a .project file so one can import it.  Is the index.html editable or is it somehow generated?

![image](https://github.com/eclipse-birt/birt/assets/208716/7024237e-8570-4d5c-99f0-a9520fed4c9d)

There's no favicon:

![image](https://github.com/eclipse-birt/birt/assets/208716/3fc1daf7-762a-452e-af49-d1846d8ab89a)

 So I'd like to add one as in the diff above...

**Comment by merks** [comment]
I'm not sure which features in the repository are intended to be installed in an IDE, but if I try to install them **all**, it fails like this:

> Cannot complete the request.  Generating details.
> ERROR: org.eclipse.equinox.p2.director code=10053 Cannot complete the install because one or more required items could not be found.
>   at org.eclipse.oomph.util.OomphPlugin.coreException(OomphPlugin.java:296)
>   at org.eclipse.oomph.p2.internal.core.ProfileTransactionImpl.resolve(ProfileTransactionImpl.java:446)
>   at org.eclipse.oomph.p2.internal.core.ProfileTransactionImpl.commit(ProfileTransactionImpl.java:356)
>   at org.eclipse.oomph.setup.p2.impl.P2TaskImpl.perform(P2TaskImpl.java:904)
>   at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.doPerformNeededSetupTasks(SetupTaskPerformer.java:3864)
>   at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.performNeededSetupTasks(SetupTaskPerformer.java:3792)
>   at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.performTriggeredSetupTasks(SetupTaskPerformer.java:3773)
>   at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.perform(SetupTaskPerformer.java:3651)
>   at org.eclipse.oomph.setup.ui.wizards.ProgressPage$9.run(ProgressPage.java:592)
>   at org.eclipse.oomph.setup.ui.wizards.ProgressPage$11$1.run(ProgressPage.java:721)
>   at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
>   ERROR: org.eclipse.equinox.p2.director code=0 Software being installed: artificial_root 1.0.0.v1686307550093
>   ERROR: org.eclipse.equinox.p2.director code=0 Missing requirement: Apache POI 4.1.1.v20221112-0806 (org.apache.poi 4.1.1.v20221112-0806) requires 'java.package; org.apache.commons.collections4 [4.4.0,5.0.0)' but it could not be found
>   ERROR: org.eclipse.equinox.p2.director code=1 Cannot satisfy dependency:
>     ERROR: org.eclipse.equinox.p2.director code=0 From: artificial_root 1.0.0.v1686307550093
>     ERROR: org.eclipse.equinox.p2.director code=0 To: org.eclipse.equinox.p2.iu; org.eclipse.birt.engine.runtime.feature.group 0.0.0
>   ERROR: org.eclipse.equinox.p2.director code=1 Cannot satisfy dependency:
>     ERROR: org.eclipse.equinox.p2.director code=0 From: BIRT Engine Runtime 4.14.0.v202306081942 (org.eclipse.birt.engine.runtime.feature.group 4.14.0.v202306081942)
>     ERROR: org.eclipse.equinox.p2.director code=0 To: org.eclipse.equinox.p2.iu; org.apache.poi [4.1.1.v20221112-0806,4.1.1.v20221112-0806]

I guess I should restrict it to the ones listed here:

https://www.eclipse.org/setups/marketplace/?id=5586359

**Comment by wimjongman** [comment]
Yes that installs, but that one has too little. It also requires the datatools bundles because, strangely enough, some icons are used from there.

**Comment by merks** [comment]
@wimjongman 

The problem is there is no org.apache.commons.collections4  in the BIRT repo, in the release train repo, nor in the data tools repo.  So I will try to include it in the features that include poi and test again...

BTW, did you see my comment https://github.com/eclipse-birt/birt/issues/1286#issuecomment-1582491056 ?  I'd like to understand how the website works and how to edit/generate it...

**Comment by merks** [comment]
FYI, this is the only unsigned content left:

![image](https://github.com/eclipse-birt/birt/assets/208716/cdcf5ede-f9a3-43e6-949f-72989cb53b5a)

and these are because they use old weak signatures not recognized as signed by recent JREs.  Only PGP signatures could address that...  Some of these very old dependencies really need a refresh; another thing to discuss with respect to Orbit...

**Comment by wimjongman** [comment]
👍Looks good. Thanks!

**Comment by wimjongman** [comment]
Ah, you got 20-minute Yoga breaks? Excellent.

**Comment by merks** [comment]
@wimjongman 

FYI, the latest nightly build as no unsigned content:

![image](https://github.com/eclipse-birt/birt/assets/208716/698cc6b9-b29d-4e15-8cd3-05c8a4c7a5a8)

**Comment by wimjongman** [comment]
Wow that is amazing. How did you do that? Could you upgrade those old bundles?

**Comment by merks** [comment]
I mirrored the last Orbit release with old CVS content (the same one the Platform uses) PGP signed all bundles (so it works forever even if the jar signatures go stale) and added new checksums so no md5 warnings all just using cool Tycho features. 

https://ci.eclipse.org/oomph/job/simrel/job/simrel-orbit-legacy/

Where there’s a will there’s a way.

**Comment by speckyspooky** [comment]
@merks 
I figured out one file which isn't included in oru automated version update.
It is the index.jsp of the birt viewer.

Ther the version numbers are added like JSP--variable-declarations.
I will change the file because I will renew the old index page in style of the new built-side.
And I will also pimp a little bit the example reports.

**Comment by merks** [comment]
You deleted these two test*.rptdesign files:

![image](https://github.com/eclipse-birt/birt/assets/208716/77443f27-a551-4eb2-b2c8-be28fc2b2e4c)

The test1.rptdesign file is mentioned in the build.properties so should be removed from there if you delete it.

The test.rptdesign file, as the error message suggests, is mentioned in an ant script to that copies it, apparently as a hello world sample

![image](https://github.com/eclipse-birt/birt/assets/208716/0599d144-9a66-47da-b7d8-1dec60d2141d)

Probably you shouldn't delete that one but rather update it with the new styling...  Other things seem to expect it to exist:

![image](https://github.com/eclipse-birt/birt/assets/208716/69034ce9-b717-4a49-80a5-305b17bae322)

Probably the file names are poor; they make searching find many unrelated matches...

**Comment by speckyspooky** [comment]
I will to 2 changes like a try. I will change the build.properties & the build.xml to the new name.
I doesn't change the name "hello_world_rptdesign". But on this try I would emain the new names.

If the new commit won't work, I will rename to "test.rptdesign" and "test1.rptdesign".

Where you have found the copy issue, there are special log files so that I can see it?

**Comment by merks** [comment]
The GitHub action log shows this:

![image](https://github.com/eclipse-birt/birt/assets/208716/334eaa8d-e011-4bdc-b9f9-92f275172618)

The ci job log also shows this:

![image](https://github.com/eclipse-birt/birt/assets/208716/ffa67f2d-8dbe-44f3-bd6c-e8f7bc7b169f)

Each can be opened from the link in the PR.

I suspect the build.properties mention of test1.rptdesign was just careless and isn't needed.  But it also doesn't hurt to mention new new name just in case (though the test.rptdesign wasn't mentioned).   

A meaningful new name is a good idea!

**Comment by speckyspooky** [comment]
Thanks, so I know now where I can check the next build.

The new "build is running" (with the new file names - crossed fingers).

**Comment by merks** [comment]
BTW, this issue prompted me to look at whether we could enable this test of the two runtimes:

![image](https://github.com/eclipse-birt/birt/assets/208716/2940ddc1-b091-4845-9b65-c80b19313c30)

But it fails for the OSGi runtime.  I'm concerned that this could be an actual problem of something missing.  In particular the org.eclipse.core.runtime is missing from the computed URLs...

**Comment by speckyspooky** [comment]
This testcase would be nice.

The new build finished successful on the PR. So if you could checkit for approval, I can go ahead with the merge.

**Comment by merks** [comment]
I see org.eclipse.emf.ecore in these places where I would also expect org.eclipse.core.runtime in those places:

> merks@CORE MINGW64 /d/Users/merks/birt-master/git/birt/build/birt-packages/birt-runtime-osgi (master)
> $find . -name  org.eclipse.emf.ecore_*
> ./target/package/ReportEngine/lib/org.eclipse.emf.ecore_2.34.0.v20230406-1203.jar
> ./target/package/ReportEngine/platform/plugins/org.eclipse.emf.ecore_2.34.0.v20230406-1203.jar
> ./target/package/WebViewerExample/WEB-INF/lib/org.eclipse.emf.ecore_2.34.0.v20230406-1203.jar
> ./target/package/WebViewerExample/WEB-INF/platform/plugins/org.eclipse.emf.ecore_2.34.0.v20230406-1203.jar
> ./target/products/org.eclipse.birt.engine.runtime/win32/win32/x86_64/ReportEngine/plugins/org.eclipse.emf.ecore_2.34.0.v20230406-1203.jar
> 
> merks@CORE MINGW64 /d/Users/merks/birt-master/git/birt/build/birt-packages/birt-runtime-osgi (master)
> $find . -name  org.eclipse.core.runtime_*
> ./target/package/ReportEngine/platform/plugins/org.eclipse.core.runtime_3.27.0.v20230515-1719.jar
> ./target/package/WebViewerExample/WEB-INF/platform/plugins/org.eclipse.core.runtime_3.27.0.v20230515-1719.jar
> ./target/products/org.eclipse.birt.engine.runtime/win32/win32/x86_64/ReportEngine/plugins/org.eclipse.core.runtime_3.27.0.v20230515-1719.jar


I see this in the log when building so something is not quite right missing at least org.eclipse.core.runtime:

> 
> 
> build-report-engine:
>      [copy] Copying 360 files to D:\Users\merks\birt-master\git\birt\build\birt-packages\birt-runtime-osgi\target\package\ReportEngine\platform\plugins
>      [copy] Copying 37 files to D:\Users\merks\birt-master\git\birt\build\birt-packages\birt-runtime-osgi\target\package\ReportEngine\lib
>      [copy] Copying 3 files to D:\Users\merks\birt-master\git\birt\build\birt-packages\birt-runtime-osgi\target\package\ReportEngine\platform\configuration
>      [copy] Copying 1 file to D:\Users\merks\birt-master\git\birt\build\birt-packages\birt-runtime-osgi\target\package\ReportEngine\platform\configuration
>      [copy] Copying 1 file to D:\Users\merks\birt-master\git\birt\build\birt-packages\birt-runtime-osgi\target\package\ReportEngine\samples
>      [copy] Copying 1 file to D:\Users\merks\birt-master\git\birt\build\birt-packages\birt-runtime-osgi\target\package\ReportEngine
>      [copy] Copying 1 file to D:\Users\merks\birt-master\git\birt\build\birt-packages\birt-runtime-osgi\target\package\ReportEngine
> 
> build-webviewer:
>      [echo] D:\Users\merks\birt-master\git\birt\viewer\org.eclipse.birt.report.viewer, D:\Users\merks\birt-master\git\birt\build\birt-packages\birt-runtime-osgi\target\package\WebViewerExample
>      [copy] Copying 160 files to D:\Users\merks\birt-master\git\birt\build\birt-packages\birt-runtime-osgi\target\package\WebViewerExample
>      [copy] Copying 37 files to D:\Users\merks\birt-master\git\birt\build\birt-packages\birt-runtime-osgi\target\package\WebViewerExample\WEB-INF\lib
>      [copy] Copying 363 files to D:\Users\merks\birt-master\git\birt\build\birt-packages\birt-runtime-osgi\target\package\WebViewerExample\WEB-INF
>      [copy] Copying 2 files to D:\Users\merks\birt-master\git\birt\build\birt-packages\birt-runtime-osgi\target\package\WebViewerExample\WEB-INF\lib
>      [copy] Copying 3 files to D:\Users\merks\birt-master\git\birt\build\birt-packages\birt-runtime-osgi\target\package
>      [copy] Copying 1 file to D:\Users\merks\birt-master\git\birt\build\birt-packages\birt-runtime-osgi\target\package\about_files
>      [copy] Copying 1 file to D:\Users\merks\birt-master\git\birt\build\birt-packages\birt-runtime-osgi\target\package
> 
> build-webviewer-war:
>      [copy] Copying 1 file to D:\Users\merks\birt-master\git\birt\build\birt-packages\birt-runtime-osgi\target\package\WebViewerExample\WEB-INF
>       [jar] Building jar: D:\Users\merks\birt-master\git\birt\build\birt-packages\birt-runtime-osgi\target\package\birt.war

**Comment by speckyspooky** [comment]
Please take a look into my changes, I have only enhanced the 2 points from your note above which causes the osgi-issue of the test.rptdesign.
But I have seen that the special instruction of file copy is only added on the osgi-product.

So I didn't know exactly what I can do on your new findings - yes, I can rollback all my changes...if you want.

**Comment by merks** [comment]
I don't expect you to do anything about my findings.  I think this is maybe broken and I think maybe it has been for a long time already.  Definitely go ahead with your changes!

**Comment by speckyspooky** [comment]
Ok, I understand and go ahead.

If you have an idea how I can support you let me know.

**Comment by merks** [comment]
My sense is that this test of the OSGi runtime never really worked and is maybe not actually very sensible.  Certainly the URL classloader it's creating is very incomplete and is missing everything in the birt-runtime-osgi/ReportEngine/platform/plugins folder.  When that's added, some things still fail and that seems related to nested jars in the Bundle-ClassPath not being found ,which is not surprising when only the containing bundle is on the classpath.

E.g., this fails to load:
```
Manifest-Version: 1.0
Bundle-ManifestVersion: 2
Bundle-Name: %Bundle-Name
Bundle-SymbolicName: org.eclipse.birt.report.engine; singleton:=true
Bundle-Version: 4.14.0.qualifier
Bundle-ClassPath: enginetesthelper.jar,
 .,
 lib/Tidy.jar,
 lib/commons-cli-1.0.jar
```
I don't want to bang my head against the wall on something that doesn't make sense...

**Comment by merks** [comment]
The other runtime passes the test so I'm somewhat tempted to disable the OSGi part, but better would be to actually test it.  Anyway, I've had to put that on the back burner with too much else to do...

I have looked at how to get a newer version of poi, which is a bit of tangles nightmare of dependencies, so that is a work in progress.  Also, I thought getting a new derby would be easy, but I don't know if their bundle is actually functional.  It's certainly poorly named and is problematic to get through the IP review process:

https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/8773

**Comment by wimjongman** [comment]
Yeah, I don't really know the history of the OSGi runtime, nor if it is used by anybody. It is sure that the OSGi runtime is embedded in the IDE but I'm not sure what its advantage is vs the non-osgi runtime.

Maybe @thelaserninja knows?

**Comment by chloetz** [comment]
Just for information: all our users (approx. 350 000) use the OSGi runtime.

Von: Wim Jongman ***@***.***
Gesendet: Mittwoch, 14. Juni 2023 08:54
An: eclipse-birt/birt
Cc: Loetz, Christophe; Team mention
Betreff: Re: [eclipse-birt/birt] Improve the release engineering (Issue #1286)


Yeah, I don't really know the history of the OSGi runtime, nor if it is used by anybody. It is sure that the OSGi runtime is embedded in the IDE but I'm not sure what its advantage is vs the non-osgi runtime.

Maybe @TheLaserNinja<https://github.com/TheLaserNinja> knows?

**Comment by speckyspooky** [comment]
> 
> I have looked at how to get a newer version of poi, which is a bit of tangles nightmare of dependencies, so that is a work in progress...
> 
Thanks for your investigation on it, yes the apache poi has many dependencies. So it could be if we would have a newer version on BIRT side we have to change/optimize some project parts e.g. the excel emitters of (own & spudsoft)

**Comment by wimjongman** [comment]
I think we are done here. Thanks Ed, and all other involved.
